export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';

export const POST_PRODUCT = 'POST_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const SET_PRODUCT = 'SET_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const DELETE_PRODUCT_FORM = 'DELETE_PRODUCT_FORM';
export const SET_PRODUCT_FORM = 'SET_PRODUCT_FORM';

export const SET_FILTERS = 'SET_FILTERS';
export const GET_PRODUCTS_BY_FILTER = 'GET_PRODUCTS_BY_FILTER';
export const GET_DATA = 'GET_DATA';

export const POST_USER = 'POST_USER';
export const GET_USER = 'GET_USER';
export const SET_USER = 'SET_USER';

export const LOGOUT = 'LOGOUT';
export const SET_LANG = 'SET_LANG';
export const SET_ALL_CATEGORIES = 'SET_ALL_CATEGORIES';
export const SET_ALL_COLLECTIONS = 'SET_ALL_COLLECTIONS';
export const SET_LOADING_DATA = 'SET_LOADING_DATA';
export const SET_LOGIN_FORM = 'SET_LOGIN_FORM';
export const SET_REGISTRATION_FORM = 'SET_REGISTRATION_FORM';

export const GET_CART = 'GET_CART';
export const SET_CART = 'SET_CART';
export const DELETE_CART = 'DELETE_CART';
export const UPDATE_CART = 'UPDATE_CART';

export const TOGGLE_FILTER = 'TOGGLE_FILTER';

export const SET_PRODUCTS_ERROR = 'SET_PRODUCTS_ERROR';

export const SET_CATEGORY_FORM = 'SET_CATEGORY_FORM';
export const POST_CATEGORY_FORM = 'POST_CATEGORY_FORM';
export const DELETE_CATEGORY_FORM = 'DELETE_CATEGORY_FORM';

export const SET_COLLECTION_FORM = 'SET_COLLECTION_FORM';
export const DELETE_COLLECTION_FORM = 'DELETE_COLLECTION_FORM';
export const POST_COLLECTION_FORM = 'POST_COLLECTION_FORM';
