export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCTS_BY_FILTER = 'GET_PRODUCTS_BY_FILTER';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_FILTER = 'SET_FILTER';
export const SET_LOADING_DATA = 'SET_LOADING_DATA';

export const SET_PRODUCTS_ERROR = 'SET_PRODUCTS_ERROR';